### PR TITLE
Mask the Kubernetes Secrets data from dry-run and apply logs

### LINKED ISSUE #419: Secrets included in log messages and notifications
Related to https://github.com/fluxcd/kustomize-controller/pull/407

I'm using notification controller in pair, today on slack I've observed:

```
kustomization/flux-system.flux-system
apply failed: 
Error from server (InternalError): error when applying patch:
{"stringData":{"XXX":"XXX"}}
to:
Resource: "/v1, Resource=secrets", GroupVersionKind: "/v1, Kind=Secret"
Name: "XXX", Namespace: "XXX"
for: "d0cb7c41-b7cc-453a-93dd-fa1d98256df4.yaml": Internal error occurred: rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

Example from @auvik-bheesham:
```
2021-08-12T20:53:21.349-0400    ERROR   controller-runtime.manager.controller.kustomization     Reconciliation failed after 580.457076ms, next try in 0s     {
"reconciler group": "kustomize.toolkit.fluxcd.io", "reconciler kind": "Kustomization", "name": "sops-d98cs", "namespace": "sops-dkgvw", "revision": "main/9db2
8d39cb66806297385330a532647516c7c814", "error": "apply failed: Error from server (BadRequest): error when creating \"0f1563ce-8273-4879-99dd-f6f58629cc2d.yaml
\": Secret in version \"v1\" cannot be handled as a Secret: v1.Secret.StringData: ReadString: expects \" or n, but found 0, error found in #10 byte of ...|\"s
ecret\":0}}\n|..., bigger context ...|\"namespace\":\"sops-dkgvw\"},\"stringData\":{\"secret\":0}}\n|...\n"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /Users/bheesham/dev/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:298
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /Users/bheesham/dev/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /Users/bheesham/dev/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:214
2021-08-12T20:53:21.349-0400    DEBUG   controller-runtime.manager.events       Normal  {"object": {"kind":"Kustomization","namespace":"sops-dkgvw","name":"so
ps-d98cs","uid":"0f1563ce-8273-4879-99dd-f6f58629cc2d","apiVersion":"kustomize.toolkit.fluxcd.io/v1beta1","resourceVersion":"371"}, "reason": "error", "messag
e": "apply failed: Error from server (BadRequest): error when creating \"0f1563ce-8273-4879-99dd-f6f58629cc2d.yaml\": Secret in version \"v1\" cannot be handl
ed as a Secret: v1.Secret.StringData: ReadString: expects \" or n, but found 0, error found in #10 byte of ...|\"secret\":0}}\n|..., bigger context ...|\"name
space\":\"sops-dkgvw\"},\"stringData\":{\"secret\":0}}\n|...\n"}
```

### PR DESCRIPTION
**Pull request by michalschott**
Different approach to fix #419

### CODE REVIEW

**Review by stefanprodan — COMMENTED** [review]
@michalschott this is good start, can you please write some tests to ensure we don't replace all the lines in the error string? For a Kustomization that includes an invalid Secret, ConfigMap and Deployment only the Secret data should be replaced.

**Comment by michalschott** [comment]
Hey,

Just pushed an update / rebase. Now output looks like this:

```
{"level":"error","ts":"2021-09-03T12:32:09.349+0200","logger":"controller.kustomization","msg":"Reconciliation failed after 265.930013ms, next try in 15s","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"backend","namespace":"default","revision":"master/b241d5f983ace900e699cf32b398ebdf24d9a5d9","error":"apply failed: Error from server (BadRequest): error when creating \"934440a6-3b77-4597-bfdd-895d0629c44d.yaml\": Secret in version \"v1\" cannot be handled as a Secret: v1.Secret.Data:  [ ** REDACTED ** ]\n"}

{"level":"error","ts":"2021-09-03T12:32:55.272+0200","logger":"controller.kustomization","msg":"Reconciliation failed after 215.382556ms, next try in 15s","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"backend","namespace":"default","revision":"master/7cb4e2d4a9f361fd2db37e5e4805bbc192717348","error":"apply failed: Error from server (BadRequest): error when creating \"934440a6-3b77-4597-bfdd-895d0629c44d.yaml\": Secret in version \"v1\" cannot be handled as a Secret: v1.Secret.StringData:  [ ** REDACTED ** ]\n|..., bigger context ...|et-2\",\"namespace\":\"default\"},\"stringData\":{ [ ** REDACTED ** ] }\n|...\n"}
```

Having tests would be useful indeed, will see what can I do.

**Review by stefanprodan — COMMENTED** [review]
@michalschott malformed secrets will not pass validation, can you please use  `stripSensitiveData` for the validation error also?

**Comment by michalschott** [comment]
> @michalschott malformed secrets will not pass validation, can you please use `stripSensitiveData` for the validation error also?

Good spot, actioned.

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @michalschott 🏅

File: controllers/utils.go [hunk 1]
```diff
@@ -77,3 +79,14 @@ func containsString(slice []string, s string) bool {
 	}
 	return false
 }
+
+func stripSensitiveData(err error) error {
```
Comment (hiddeco) [inline controllers/utils.go:83]: Not important for this PR, as we are foreseeing that it will be refactored soon (or handled differently), but in cases like this I would pick `maskSensitiveData` over the current function name.

As a strip would literally take all data out, instead of replacing (= masking) it.

**Review by hiddeco — APPROVED** [review]
