### PR TITLE
Fix performance regression due to using client without cache

### LINKED ISSUE #1428: Slower Reconciles with v1.5.1
When upgrading from kustomize-controller `1.5.0` to `1.5.1`, we're seeing a significant slowdown in reconcile times.

Using one Kustomization as an example, which manages ~1500 NetworkPolicies:

Average reconcile time on `1.5.0`: 25s
Average reconcile time on `1.5.1`: 2m30s

Example Kustomization setup:

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: example-kustomize
spec:
  force: false
  interval: 60m
  path: ./path/to/netpols
  prune: true
  sourceRef:
    kind: GitRepository
    name: example-repo
```

### PR DESCRIPTION
**Pull request by matheuscscp**
Fixes #1428

### CODE REVIEW

File: internal/controller/kustomization_controller.go [hunk 1]
```diff
@@ -1160,6 +1180,24 @@ func (r *KustomizationReconciler) patch(ctx context.Context,
 	return nil
 }
 
+func (r *KustomizationReconciler) getClientAndPoller(
```
Comment (stefanprodan) [inline internal/controller/kustomization_controller.go:1183]: Please add a comment to this function, explain what it does

Comment (matheuscscp) [reply internal/controller/kustomization_controller.go:1188]: Fixed, thanks!

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @matheuscscp 🏅
