### PR TITLE
Requeue on cancellation to avoid stale cache race condition

### LINKED ISSUE #1624: Specific Kustomizations hang with "New reconciliation triggered"
```
flux --version
flux version 2.8.3
```

Since enabling server-side-apply on my HelmReleases, some Kustomizations have been getting stuck with the status `New reconciliation triggered by GitRepository/flux-system/flux-system`. For me, it is specifically my External-Secrets Kustomization, which applies a HelmRelease, OCIRepository, and GrafanaDashboard resource. 

I am only able to reproduce this with the `CancelHealthCheckOnNewRevision` feature-gate **and** SSA enabled on the HelmRelease. It only gets triggered with multiple commits before all the healthChecks in my cluster timeout, triggering the `CancelHealthCheckOnNewRevision` featureGate. Note the external-secrets Kustomization in question is already reconciled before the commit triggering the featureGate. From the logs, my elementary analysis is that the new reconciliation after the healthchecks are cancelled just never gets triggered here.
When manually reconciling via the cli when stuck `flux reconcile ks external-secrets`, the Kustomization reconciles immediately.

My repo is structured with a Kustomization per HelmRelease, and it happens only on my [External-Secrets](https://github.com/external-secrets/external-secrets) Kustomization. Others I have talked to with similar repos have observed it on External-Secrets, [Cloudnative-PG](https://github.com/cloudnative-pg/cloudnative-pg), [Dragonfly-operator](https://github.com/dragonflydb/dragonfly-operator), and [Volsync](https://github.com/backube/volsync). The only similarities I can come up with between those apps is templated CRDs in the chart and common applications for other Kustomziations to set in dependsOn.

My deployment in-question is here https://github.com/aclerici38/home-ops/tree/main/kubernetes/apps/cluster-infra/external-secrets/app
(The Kustomization comes from a kustomize component https://github.com/aclerici38/home-ops/tree/main/kubernetes/components/ks)
I am deploying flux through the operator and chart for the fluxInstance
https://github.com/aclerici38/home-ops/tree/main/kubernetes/apps/flux-system

Reproduction steps:
1. set `--feature-gates=CancelHealthCheckOnNewRevision=true` on the kustomize controller
2. Deploy a Kustomization that applies a HelmRelease to install External-Secrets with CRDs enabled
3. Set `spec.upgrade.serverSideApply` to `enabled`
4. Commit to *any* part of the repo to trigger reconciliations
5. Make another commit before all Kustomizations are reconciled, triggering the `CancelHealthCheckOnNewRevision`
6. Observe External-secrets Kustomization stuck with `New reconciliation triggered by GitRepository/flux-system/flux-system` in the status
7. Run `flux reconcile kustomization external-secrets` 
8. Observe a successful reconciliation immediately

Kustomization when stuck:
```
k get ks -n cluster-infra external-secrets -o yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  annotations:
    reconcile.fluxcd.io/requestedAt: "2026-03-15T11:09:35.364675-07:00"
  creationTimestamp: "2025-12-13T20:19:09Z"
  finalizers:
  - finalizers.fluxcd.io
  generation: 6
  labels:
    components.dormammu/ks: app
    kustomize.dormammu/app-vars: "true"
    kustomize.toolkit.fluxcd.io/name: cluster-infra
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: external-secrets
  namespace: cluster-infra
  resourceVersion: "120857546"
  uid: d87ac9a8-333d-4f95-a127-a11e6b043ed9
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: external-secrets
      app.kubernetes.io/namespace: cluster-infra
  components:
  - ../../../../components/hr
  dependsOn: []
  force: false
  interval: 30m
  path: ./kubernetes/apps/cluster-infra/external-secrets/app
  postBuild:
    substitute:
      APP_URL: external-secrets.REDACTED
    substituteFrom:
    - kind: ConfigMap
      name: external-secrets-app-vars-8mt975ht5k
      optional: false
    - kind: Secret
      name: cluster-settings
      optional: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: cluster-infra
  timeout: 3m
  wait: true
status:
  conditions:
  - lastTransitionTime: "2026-03-24T13:22:22Z"
    message: Running health checks for revision refs/heads/main@sha1:124a229e1226e2a91d04c13a75eb4520cb8f0839
      with a timeout of 3m0s
    observedGeneration: 6
    reason: ProgressingWithRetry
    status: "True"
    type: Reconciling
  - lastTransitionTime: "2026-03-24T13:22:22Z"
    message: New reconciliation triggered by GitRepository/flux-system/flux-system
    observedGeneration: 6
    reason: HealthCheckCanceled
    status: "False"
    type: Ready
  - lastTransitionTime: "2026-03-24T13:22:22Z"
    message: Running health checks for revision refs/heads/main@sha1:124a229e1226e2a91d04c13a75eb4520cb8f0839
      with a timeout of 3m0s
    observedGeneration: 6
    reason: Progressing
    status: Unknown
    type: Healthy
  history:
  - digest: sha256:f8a3ea6188bbb3496502e086c607474de8e345aa57a3df11f423342d1cfa5c88
    firstReconciled: "2026-03-20T19:29:32Z"
    lastReconciled: "2026-03-24T13:21:36Z"
    lastReconciledDuration: 278.288099ms
    lastReconciledStatus: ReconciliationSucceeded
    metadata:
      revision: refs/heads/main@sha1:f2a25a8beb1f6bf92091e4c2d87e60911553e5fd
    totalReconciliations: 212
  - digest: sha256:fcc55296250f7cea8d36486acc933275ee66c344faaf8ab20322f639ac3a6ec4
    firstReconciled: "2026-03-19T22:24:54Z"
    lastReconciled: "2026-03-20T18:59:45Z"
    lastReconciledDuration: 134.966415ms
    lastReconciledStatus: ReconciliationSucceeded
    metadata:
      revision: refs/heads/main@sha1:f5737db9fdaae67f81093e35fbc2f23f7e52b5e9
    totalReconciliations: 60
  - digest: sha256:1106cff91949f4aeb7e636e13f25e5aab3009998a66a275e4b6e28b3b941c234
    firstReconciled: "2026-03-16T18:51:06Z"
    lastReconciled: "2026-03-19T22:19:33Z"
    lastReconciledDuration: 114.31534ms
    lastReconciledStatus: ReconciliationSucceeded
    metadata:
      revision: refs/heads/main@sha1:02994e83fb13e08815cfbd954ede85589944b9fd
    totalReconciliations: 180
  - digest: sha256:f06297926ef50591f513d62340fc1980a215180815ec78e7e13a94f4d35bcddd
    firstReconciled: "2026-03-19T08:35:23Z"
    lastReconciled: "2026-03-19T21:09:53Z"
    lastReconciledDuration: 338.91764ms
    lastReconciledStatus: ReconciliationSucceeded
    metadata:
      revision: refs/heads/main@sha1:42140223327314998a0b1b44867be7a047db2aca
    totalReconciliations: 65
  - digest: sha256:2eb7d794a295d11fd693ec7344236922618dd2c05283e8dc577a9a1fa1ac427a
    firstReconciled: "2026-03-15T16:21:29Z"
    lastReconciled: "2026-03-16T18:35:16Z"
    lastReconciledDuration: 130.317971ms
    lastReconciledStatus: ReconciliationSucceeded
    metadata:
      revision: refs/heads/main@sha1:ef17f4878933bc497197cccf856983ccb4d88ac5
    totalReconciliations: 14
  inventory:
    entries:
    - id: cluster-infra_external-secrets_grafana.integreatly.org_GrafanaDashboard
      v: v1beta1
    - id: cluster-infra_external-secrets_helm.toolkit.fluxcd.io_HelmRelease
      v: v2
    - id: cluster-infra_external-secrets_source.toolkit.fluxcd.io_OCIRepository
      v: v1
  lastAppliedRevision: refs/heads/main@sha1:f2a25a8beb1f6bf92091e4c2d87e60911553e5fd
  lastAttemptedRevision: refs/heads/main@sha1:124a229e1226e2a91d04c13a75eb4520cb8f0839
  lastHandledReconcileAt: "2026-03-15T11:09:35.364675-07:00"
  observedGeneration: 6
```
HelmRelease when stuck:
```
k get hr -n cluster-infra external-secrets -o yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    reconcile.fluxcd.io/forceAt: "1772044083"
    reconcile.fluxcd.io/requestedAt: "1772044083"
  creationTimestamp: "2025-12-13T20:25:15Z"
  finalizers:
  - finalizers.fluxcd.io
  generation: 21
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/namespace: cluster-infra
    kustomize.toolkit.fluxcd.io/name: external-secrets
    kustomize.toolkit.fluxcd.io/namespace: cluster-infra
  name: external-secrets
  namespace: cluster-infra
  resourceVersion: "120819928"
  uid: c9d3d662-00c5-4612-af13-3115c0a92c78
spec:
  chartRef:
    kind: OCIRepository
    name: external-secrets
  driftDetection:
    mode: enabled
  install:
    crds: CreateReplace
    disableTakeOwnership: true
    remediation:
      retries: 1
    serverSideApply: true
    strategy:
      name: RetryOnFailure
    timeout: 2m
  interval: 1h
  maxHistory: 1
  postRenderers:
  - kustomize:
      patches:
      - patch: |
          - op: add
            path: /spec/rules/0/timeouts
            value:
              request: 0s
        target:
          group: gateway.networking.k8s.io
          kind: HTTPRoute
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    disableTakeOwnership: true
    remediation:
      retries: 1
    serverSideApply: enabled
    strategy:
      name: RemediateOnFailure
    timeout: 2m
  values:
    certController:
      image:
        repository: ghcr.io/external-secrets/external-secrets
      serviceMonitor:
        enabled: true
        interval: 1m
    image:
      repository: ghcr.io/external-secrets/external-secrets
    installCRDs: true
    leaderElect: true
    replicaCount: 2
    serviceMonitor:
      enabled: true
      interval: 1m
    webhook:
      image:
        repository: ghcr.io/external-secrets/external-secrets
      serviceMonitor:
        enabled: true
        interval: 1m
status:
  conditions:
  - lastTransitionTime: "2026-03-20T19:29:30Z"
    message: Helm upgrade succeeded for release cluster-infra/external-secrets.v16
      with chart external-secrets@2.2.0
    observedGeneration: 21
    reason: UpgradeSucceeded
    status: "True"
    type: Ready
  - lastTransitionTime: "2026-03-20T19:29:30Z"
    message: Helm upgrade succeeded for release cluster-infra/external-secrets.v16
      with chart external-secrets@2.2.0
    observedGeneration: 21
    reason: UpgradeSucceeded
    status: "True"
    type: Released
  history:
  - action: upgrade
    apiVersion: v2
    appVersion: v2.2.0
    chartName: external-secrets
    chartVersion: 2.2.0
    configDigest: sha256:cfbd9b63d5473e42e267b8433c69c43f8e88de14d7f752ef0752e3ae85feee69
    digest: sha256:ea2b41585e7816c88c44b034b3fa022f2e1f9e71fad544e4b06da76eb9ecd0f9
    firstDeployed: "2025-12-13T20:14:45Z"
    lastDeployed: "2026-03-20T19:28:57Z"
    name: external-secrets
    namespace: cluster-infra
    ociDigest: sha256:feb252e996e2ce31ea015a1e098f2c5d438389a0a2fc1f43659b3f5421046f6f
    status: deployed
    version: 16
  - apiVersion: v2
    appVersion: v2.1.0
    chartName: external-secrets
    chartVersion: 2.1.0
    configDigest: sha256:cfbd9b63d5473e42e267b8433c69c43f8e88de14d7f752ef0752e3ae85feee69
    digest: sha256:286ab5dd70b7bdbdb4572f957112782433691f43785011b25a81d5dfd1a6aeb3
    firstDeployed: "2025-12-13T20:14:45Z"
    lastDeployed: "2026-03-15T19:31:38Z"
    name: external-secrets
    namespace: cluster-infra
    ociDigest: sha256:447e6cdcc323b70bcc4f487672f7ca98ba581ba9b68789be87ce159a6caeed9c
    status: superseded
    version: 15
  inventory:
    entries:
    - id: cluster-infra_external-secrets-cert-controller__ServiceAccount
      v: v1
    - id: cluster-infra_external-secrets__ServiceAccount
      v: v1
    - id: cluster-infra_external-secrets-webhook__ServiceAccount
      v: v1
    - id: cluster-infra_external-secrets-webhook__Secret
      v: v1
    - id: _acraccesstokens.generators.external-secrets.io_apiextensions.k8s.io_CustomResourceDefinition
      v: v1
    - id: _cloudsmithaccesstokens.generators.external-secrets.io_apiextensions.k8s.io_CustomResourceDefinition
      v: v1
    - id: _clusterexternalsecrets.external-secrets.io_apiextensions.k8s.io_CustomResourceDefinition
      v: v1
    - id: _clustergenerators.generators.external-secrets.io_apiextensions.k8s.io_CustomResourceDefinition
      v: v1
    - id: _clusterpushsecrets.external-secrets.io_apiextensions.k8s.io_CustomResourceDefinition
      v: v1
    - id: _clustersecretstores.external-secrets.io_apiextensions.k8s.io_CustomResourceDefinition
      v: v1
    - id: _ecrauthorizationtokens.generators.external-secrets.io_apiextensions.k8s.io_CustomResourceDefinition
      v: v1
    - id: _externalsecrets.external-secrets.io_apiextensions.k8s.io_CustomResourceDefinition
      v: v1
    - id: _fakes.generators.external-secrets.io_apiextensions.k8s.io_CustomResourceDefinition
      v: v1
    - id: _gcraccesstokens.generators.external-secrets.io_apiextensions.k8s.io_CustomResourceDefinition
      v: v1
    - id: _generatorstates.generators.external-secrets.io_apiextensions.k8s.io_CustomResourceDefinition
      v: v1
    - id: _githubaccesstokens.generators.external-secrets.io_apiextensions.k8s.io_CustomResourceDefinition
      v: v1
    - id: _grafanas.generators.external-secrets.io_apiextensions.k8s.io_CustomResourceDefinition
      v: v1
    - id: _mfas.generators.external-secrets.io_apiextensions.k8s.io_CustomResourceDefinition
      v: v1
    - id: _passwords.generators.external-secrets.io_apiextensions.k8s.io_CustomResourceDefinition
      v: v1
    - id: _pushsecrets.external-secrets.io_apiextensions.k8s.io_CustomResourceDefinition
      v: v1
    - id: _quayaccesstokens.generators.external-secrets.io_apiextensions.k8s.io_CustomResourceDefinition
      v: v1
    - id: _secretstores.external-secrets.io_apiextensions.k8s.io_CustomResourceDefinition
      v: v1
    - id: _sshkeys.generators.external-secrets.io_apiextensions.k8s.io_CustomResourceDefinition
      v: v1
    - id: _stssessiontokens.generators.external-secrets.io_apiextensions.k8s.io_CustomResourceDefinition
      v: v1
    - id: _uuids.generators.external-secrets.io_apiextensions.k8s.io_CustomResourceDefinition
      v: v1
    - id: _vaultdynamicsecrets.generators.external-secrets.io_apiextensions.k8s.io_CustomResourceDefinition
      v: v1
    - id: _webhooks.generators.external-secrets.io_apiextensions.k8s.io_CustomResourceDefinition
      v: v1
    - id: _external-secrets-cert-controller_rbac.authorization.k8s.io_ClusterRole
      v: v1
    - id: _external-secrets-controller_rbac.authorization.k8s.io_ClusterRole
      v: v1
    - id: _external-secrets-view_rbac.authorization.k8s.io_ClusterRole
      v: v1
    - id: _external-secrets-edit_rbac.authorization.k8s.io_ClusterRole
      v: v1
    - id: _external-secrets-servicebindings_rbac.authorization.k8s.io_ClusterRole
      v: v1
    - id: _external-secrets-cert-controller_rbac.authorization.k8s.io_ClusterRoleBinding
      v: v1
    - id: _external-secrets-controller_rbac.authorization.k8s.io_ClusterRoleBinding
      v: v1
    - id: cluster-infra_external-secrets-leaderelection_rbac.authorization.k8s.io_Role
      v: v1
    - id: cluster-infra_external-secrets-leaderelection_rbac.authorization.k8s.io_RoleBinding
      v: v1
    - id: cluster-infra_external-secrets-cert-controller-metrics__Service
      v: v1
    - id: cluster-infra_external-secrets-metrics__Service
      v: v1
    - id: cluster-infra_external-secrets-webhook__Service
      v: v1
    - id: cluster-infra_external-secrets-cert-controller_apps_Deployment
      v: v1
    - id: cluster-infra_external-secrets_apps_Deployment
      v: v1
    - id: cluster-infra_external-secrets-webhook_apps_Deployment
      v: v1
    - id: _secretstore-validate_admissionregistration.k8s.io_ValidatingWebhookConfiguration
      v: v1
    - id: _externalsecret-validate_admissionregistration.k8s.io_ValidatingWebhookConfiguration
      v: v1
    - id: cluster-infra_external-secrets-metrics_monitoring.coreos.com_ServiceMonitor
      v: v1
    - id: cluster-infra_external-secrets-webhook-metrics_monitoring.coreos.com_ServiceMonitor
      v: v1
    - id: cluster-infra_external-secrets-cert-controller-metrics_monitoring.coreos.com_ServiceMonitor
      v: v1
  lastAttemptedConfigDigest: sha256:cfbd9b63d5473e42e267b8433c69c43f8e88de14d7f752ef0752e3ae85feee69
  lastAttemptedGeneration: 21
  lastAttemptedReleaseAction: upgrade
  lastAttemptedReleaseActionDuration: 33.83738943s
  lastAttemptedRevision: 2.2.0
  lastAttemptedRevisionDigest: sha256:feb252e996e2ce31ea015a1e098f2c5d438389a0a2fc1f43659b3f5421046f6f
  lastHandledForceAt: "1772044083"
  lastHandledReconcileAt: "1772044083"
  observedGeneration: 21
  observedPostRenderersDigest: sha256:50499434250e928b35e1730acd29adba98d922b80f733141437b97eb1b2eaa53
  storageNamespace: cluster-infra
```

kustomize-controller full logs:
[ks.txt](https://github.com/user-attachments/files/26217019/ks.txt)

helm-controller full logs:
[hr.txt](https://github.com/user-attachments/files/26217021/hr.txt)

I took a small screen recording in case my description wasn't clear, showing manual reconciliation works imediately
https://github.com/user-attachments/assets/4acda8b5-4f97-4d37-a7be-7518a34e4c1f

Thanks!

### PR DESCRIPTION
**Pull request by stefanprodan**
Handle health check cancellation by requeuing immediately to ensure the object is reconciled against the new revision in the eventuality of stale runtime cache that would cause the source predicate filter to drop the reconcile request.

**Note** that there is no proof that the requests gets dropped from the queue after the cancelation is triggered, so this "fix" may not do anything. I was not able to reproduce in envtest this issue as the cache doesn't become stale (this requires flaky network or etcd pressure). The scenario I'm relying on is:

```
  Rapid commits cause stale cache scenario:                              
                                                          
  1. 124a229e reconcile → health check → cancelled by V_new dispatch                                                                                                         
  2. Old code: ctrl.Result{}, nil. Dispatch item in queue.
  3. Worker picks up dispatch item → getSource → stale cache → 124a229e → build/apply (no-op)                                                                                
  4. During build/apply, ANOTHER dispatch fires (V_newer) → interrupt context cancelled                                                                                      
  5. checkHealth → already cancelled → returns *QueueEventSource                                                                                                             
  6. Reconcile() → HealthCheckCanceled → ctrl.Result{}, nil (old code)                                                                                                       
  7. V_newer dispatch item in queue                                                                                                                                          
  8. Repeat from step 3... until eventually no more dispatches, but by then ctrl.Result{}, nil means no requeue                                                              
  9. STUCK                                                                                                                                                                   
                                                          
The rapid commits keep cancelling each stale-cache reconcile. Eventually the commits stop, but the LAST cancellation returns ctrl.Result{}, nil with no requeue.
The source cache has caught up, but nothing triggers a reconcile.
                                                                                                                                                                             
Requeue: true breaks the cycle: even after the last cancellation, a requeue fires, the source cache has V_final, the reconcile applies it, health checks pass. 
```

PS. In the case where the cache is fresh and the object is already in the queue, the new reconcile request will be dropped by the controller runtime dedupe logic, so we don't risk reconciling twice the same revision.

Preview image for testing: `ghcr.io/fluxcd/kustomize-controller:rc-203b42e7`


Fix: #1624

### CODE REVIEW

File: internal/controller/kustomization_controller.go [hunk 1]
```diff
@@ -282,7 +282,12 @@ func (r *KustomizationReconciler) Reconcile(ctx context.Context, req ctrl.Reques
 		r.event(obj, revision, originRevision, eventv1.EventSeverityInfo,
 			fmt.Sprintf("Health checks canceled due to new reconciliation triggered by %s/%s/%s",
 				qes.Kind, qes.Namespace, qes.Name), nil)
-		return ctrl.Result{}, nil
+
+		// Requeue immediately to ensure the object is reconciled against the new revision in the eventuality
+		// of stale runtime cache that would cause the source predicate filter to drop the reconcile request.
+		// In the case where the cache is fresh and the object is already in the queue, the new reconcile request
+		// will be dropped by the controller runtime dedupe logic, so we don't risk reconciling twice the same revision.
+		return ctrl.Result{Requeue: true}, nil
```
Comment (matheuscscp) [inline internal/controller/kustomization_controller.go:290]:
```suggestion
		return ctrl.Result{RequeueAfter: 1}, nil
```

`Requeue: true` is deprecated, the equivalent is `RequeueAfter: 1`

Last night I also ran tons of tests with and without this fix. I never observed something being reconciled twice after the cancellation and never saw anything get stuck. Without a fix, I was also able to reproduce the issue and managed to make some Kustomizations get stuck.

**Comment by matheuscscp** [comment]
Last night I also asked Opus 4.6 to try and root-cause the issue (which we managed to reproduce). It found a conceptually more correct fix that involves entirely replacing the default event sourcing logic of controller-runtime. The fix is very complicated and I'd rather not implement it in a patch release (or at all). I prefer the fix of this PR a lot more, because I also tested it and I never saw any double reconciliation for any objects, plus nothing got stuck.

Click below to see the details of the root cause found by Opus.

<details>

```
❯ now we need to root cause it                                                                       

● Let me dig into the WrapReconciler code in fluxcd/pkg/runtime/controller — that's where the
  cancellation and enqueueing happens.

  Searched for 2 patterns, read 4 files (ctrl+o to expand)

● This is key. Let me read the full filter logic and the reconcile function's status patching.

  Read 2 files (ctrl+o to expand)

● Let me look at finalizeStatus and when Reconciling is set/cleared.

  Searched for 1 pattern, read 1 file (ctrl+o to expand)

● Let me check when LastAttemptedRevision is set and what HasRevision does.

  Searched for 2 patterns, read 1 file (ctrl+o to expand)

● Let me look at how the For() handler and predicate interact, and check ReconcileRequestedPredicate.

  Searched for 1 pattern, read 2 files (ctrl+o to expand)

● Now let me check exactly how controller-runtime calls this for Update events — this is the key.

  Searched for 1 pattern (ctrl+o to expand)

● Let me read the exact version used by this project.

  Searched for 1 pattern, read 1 file (ctrl+o to expand)

● There it is. Lines 108-110:

  reqs := map[request]empty{}
  e.mapAndEnqueue(ctx, q, evt.ObjectOld, reqs, lowPriority)
  e.mapAndEnqueue(ctx, q, evt.ObjectNew, reqs, lowPriority)

  And mapAndEnqueue (lines 140-152):
  for _, req := range e.toRequests(ctx, o) {
      _, ok := reqs[req]
      if !ok {
          q.Add(req)
          reqs[req] = empty{}
      }
  }

  For an OCIRepository Update event (v4→v5), the map function is called twice: once with the old
  OCIRepository (artifact=v4) and once with the new (artifact=v5). The reqs map deduplicates — if a
  Kustomization was already returned by the ObjectOld call, the ObjectNew call's q.Add is skipped.

  But our wrapper's dispatch() runs inside e.toRequests() — before the requests are returned. So both
   calls dispatch (cancel), but only the first call's q.Add actually fires.

  Here's the race:

  1. ObjectOld call (artifact=v4): The wrapper calls requestsForRevisionChangeOf with the old
  OCIRepo. For a Kustomization X that was health-checking v3:
    - Filter: IsReconciling=true, HasRevision(v3) against v4 → mismatch → included
    - dispatch(X) → cancels X's health check context, removes listener
    - Request for X returned
    - mapAndEnqueue: X not in reqs → q.Add(X), add X to reqs
  2. Worker goroutine (concurrent): X detects cancelled context, returns ctrl.Result{}, nil,
  finalizeStatus patches status, Done(X) runs. X was marked dirty by q.Add(X) → re-queued. Worker
  immediately picks up X → registerListener(X) → new listener registered.
  3. ObjectNew call (artifact=v5): The wrapper calls requestsForRevisionChangeOf with the new
  OCIRepo:
    - Lists Kustomizations, finds X
    - Filter: IsReconciling=true, HasRevision(v3 or v4) against v5 → mismatch → included
    - dispatch(X) → finds the new listener from step 2 → cancels X again
    - Request for X returned
    - mapAndEnqueue: X IS in reqs → q.Add(X) is SKIPPED
  4. Worker goroutine: X detects second cancellation, returns ctrl.Result{}, nil, Done(X). X was not
  marked dirty (no q.Add happened since Get). X is removed from processing. X is not in the queue.
  STUCK.

  The race window for step 2 is between q.Add(X) in step 1 and dispatch(X) in step 3. That window
  includes processing remaining items in the ObjectOld loop plus the List call and iteration in the
  ObjectNew loop — microseconds to low milliseconds. An idle worker can pick up X and register a
  listener in that time.

  This explains why:
  - More Kustomizations → wider race window → more likely to hit
  - Operators with CRDs (external-secrets, cloudnative-pg) → longer health checks → more items
  concurrently reconciling
  - Rapid commits → multiple source events → more opportunities for the race

  The RequeueAfter fix is correct — it ensures the second cancellation in step 3 returns
  RequeueAfter: 30s, so even though q.Add was skipped, the object is re-queued via q.AddAfter.

✻ Crunched for 13m 47s

❯ so the bug is in controller-runtime? can you think of a fix?                                       

● The bug is in the interaction between controller-runtime's reqs deduplication and our wrapper's
  dispatch(). The fix belongs in fluxcd/pkg/runtime/controller — we should stop wrapping
  handler.EnqueueRequestsFromMapFunc and instead implement a custom EventHandler.

  The problem: controller-runtime's Update() calls the map function twice (ObjectOld, ObjectNew) and
  deduplicates q.Add via a shared reqs map. But our dispatch() runs inside the map function, so it
  fires twice while q.Add fires once. If a worker re-registers a listener between the two calls, the
  second dispatch cancels it with no corresponding q.Add.

  The fix: implement our own EventHandler that pairs every dispatch() with a q.Add() — no
  deduplication between ObjectOld and ObjectNew. Double q.Add is harmless (the workqueue deduplicates
   internally by marking items dirty).

  Read 1 file (ctrl+o to expand)

● The current wrapper:

  func (r *reconcilerWrapper) EnqueueRequestsFromMapFunc(
      objKind string, fn handler.MapFunc) handler.EventHandler {
      return handler.EnqueueRequestsFromMapFunc(func(...) []ctrl.Request {
          reqs := fn(ctx, obj)
          for _, req := range reqs {
              r.hooks.dispatch(...)  // cancels inside toRequests
          }
          return reqs  // controller-runtime deduplicates q.Add via reqs map
      })
  }

  The fix: return a custom EventHandler instead of wrapping handler.EnqueueRequestsFromMapFunc:

  func (r *reconcilerWrapper) EnqueueRequestsFromMapFunc(
      objKind string, fn handler.MapFunc) handler.EventHandler {
      return &dispatchAndEnqueueHandler{
          mapFunc: fn,
          hooks:   r.hooks,
          objKind: objKind,
      }
  }

  type dispatchAndEnqueueHandler struct {
      mapFunc handler.MapFunc
      hooks   *queueHooks
      objKind string
  }

  func (h *dispatchAndEnqueueHandler) dispatchAndEnqueue(
      ctx context.Context, q workqueue.RateLimitingInterface, obj client.Object) {
      reqs := h.mapFunc(ctx, obj)
      payload := queueEventPayload{source: QueueEventSource{
          Kind:      h.objKind,
          Name:      obj.GetName(),
          Namespace: obj.GetNamespace(),
          ...
      }}
      for _, req := range reqs {
          h.hooks.dispatch(queueEvent{queueEventObjectEnqueued, req}, payload)
          q.Add(req)  // always Add — no cross-call deduplication
      }
  }

  func (h *dispatchAndEnqueueHandler) Update(ctx context.Context,
      evt event.UpdateEvent, q workqueue.RateLimitingInterface) {
      h.dispatchAndEnqueue(ctx, q, evt.ObjectOld)
      h.dispatchAndEnqueue(ctx, q, evt.ObjectNew)
  }

  // Create, Delete, Generic: same pattern, single call

  Each dispatch() is immediately followed by q.Add() in the same loop iteration. No shared reqs map.
  If the ObjectOld call dispatches+enqueues X, and a worker picks up X and re-registers a listener,
  the ObjectNew call dispatches X again AND calls q.Add(X) which marks X dirty. The worker's second
  cancellation is now backed by a queue entry.

  The double q.Add for the same request is harmless:
  - If X is in the queue: no-op (already queued)
  - If X is being processed: marks dirty → re-queued after Done()
  - If X is neither: added fresh
```

</details>

File: internal/controller/kustomization_controller.go (hunk 1 above)
Comment (stefanprodan) [reply internal/controller/kustomization_controller.go:290]: Let's go with `Requeue: true` in this PR as it's used everywhere. In Flux 2.9 we could replace it in all controllers.

**Comment by stefanprodan** [comment]
@matheuscscp this fix is not need in helm-controller since it had `Requeue: true` from the start: https://github.com/fluxcd/helm-controller/blob/8a0f9d044fbec659f88db3e60a028901ab42b7ec/internal/controller/helmrelease_controller.go#L433

This also explains why users only see this in kustomize-controller

**Comment by matheuscscp** [comment]
Huh! I wonder why HC already had it 🤔 Maybe AI saw it would be needed while writing tests...

**Comment by stefanprodan** [comment]
It's not possible to reproduce this in envtest, all my attempts failed because the latency is almost zero, the cache syncs in real-time. The `Requeue: true` is from copy/pasting the conventions in HC.

**Review by matheuscscp — APPROVED** [review]
LGTM 🙌
